### ISSUE TITLE
Delete functionality doesn't work on highlighted text

### ISSUE THREAD

**Issue by panosfol** [charmitro/.emacs.d#2]
The keybind ctrl+d still deletes the character that the cursor points even if there is a highlighted text

**Comment by charmitro** [comment]
_"Doesn't work"_ is actually wrong here.

For Emacs to allow deletion of marked regions via `C-d`== _`term-delchar-or-maybe-eof`_ you need to enable the minor-mode **delete-selection-mode**.

So, if this is something you want to have in your config(I want) you can do so in your custom config file where you save everything unrelated to this configuration, or create a PR where you set a default variable in the **lisp/init-editor.el**.
